fix: all gitea binary paths point to TRIM_APPDEST/gitea

diff --git a/gitea/cmd/main b/gitea/cmd/main
--- a/gitea/cmd/main
+++ b/gitea/cmd/main
@@ -130,10 +130,10 @@ start)
     fi
     ;;
 stop)
-    pkill -9 -f "${TRIM_APPDEST}/app/gitea web" || echo "pkill fail $?"
+    pkill -9 -f "${TRIM_APPDEST}/gitea web" || echo "pkill fail $?"
     ;;
 status)
-    processNum=$(pgrep -c -f "${TRIM_APPDEST}/app/gitea web")
+    processNum=$(pgrep -c -f "${TRIM_APPDEST}/gitea web")
     if [[ ! $processNum -eq 0 ]]; then
         echo "gitea is already running"
         exit 0
